<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    protected function iniSet(string $varName, string $newValue): void
    {
        parent::iniSet($varName, $newValue); // TODO: Change the autogenerated stub
    }
}
